theme: jekyll-theme-minimal
# Site settings
title: Thao Nguyen's Portfolio
#author:
#  name: Thao Nguyen
#linkedin: https://www.linkedin.com/in/nguyenthunhatthao/
logo: "/image/Thao-profile-image.jpg"
description: Portfolio space of Thao | Data can tell
  <br><br> 
  <a href="https://www.linkedin.com/in/nguyenthunhatthao/">LinkedIn Profile</a>

  
