theme: jekyll-theme-minimal
# Site settings
title: Thao Nguyen's Portfolio
#author:
#  name: Thao Nguyen
#linkedin: https://www.linkedin.com/in/nguyenthunhatthao/
logo: "https://github.com/nhthaonguyen/nhthaonguyen.github.io/blob/main/image/Thao-profile-image.jpg?raw=true"
description: | Data can tell |
  <br><br> 
  <a href="https://www.linkedin.com/in/nguyenthunhatthao/">LinkedIn Profile</a>
  
  <a href="https://public.tableau.com/app/profile/nguyen.thu.nhat.thao">Tableau Public</a>

  
